// SPDX-License-Identifier: MIT
// Copyright 2025 RnD Center "ELVEES", JSC

#pragma once

// Base number of driver error codes.
#define ESBIMGBOOTBASE 0x10000

enum sbl_s2_status_codes {
	ESBIMGBOOT_NO_ERR = ESBIMGBOOTBASE,
	ESBIMGBOOT_LOAD_FINISH,
	ESBIMGBOOT_LOAD_CONTINUE,
	ESBIMGBOOT_IMAGE_BAD_HEADER_ID,
	ESBIMGBOOT_IMAGE_BAD_HEADER_HASH,
	ESBIMGBOOT_IMAGE_BAD_TYPE,
	ESBIMGBOOT_ROOT_CERT_IS_NOT_FIRST,
	ESBIMGBOOT_ROOT_CERT_X509_ERR,
	ESBIMGBOOT_ROOT_CERT_BAD_HASH,
	ESBIMGBOOT_ROOT_CERT_REVOKED,
	ESBIMGBOOT_NON_ROOT_CERT_TOO_MUCH_CERTS,
	ESBIMGBOOT_NON_ROOT_CERT_IS_FIRST,
	ESBIMGBOOT_NON_ROOT_CERT_X509_ERR,
	ESBIMGBOOT_ENC_KEY_BAD_CERT_CHAIN,
	ESBIMGBOOT_ENC_KEY_NO_CERT_CHAIN,
	ESBIMGBOOT_ENC_KEY_IS_NOT_SIGNED,
	ESBIMGBOOT_ENC_KEY_BAD_HASH,
	ESBIMGBOOT_ENC_KEY_BAD_SIGNATURE,
	ESBIMGBOOT_PAYLOAD_HEADER_ERR,
	ESBIMGBOOT_PAYLOAD_BAD_CERT_CHAIN,
	ESBIMGBOOT_PAYLOAD_NO_CERT_CHAIN,
	ESBIMGBOOT_PAYLOAD_IS_NOT_SIGNED,
	ESBIMGBOOT_PAYLOAD_IS_NOT_ENCRYPTED,
	ESBIMGBOOT_PAYLOAD_BAD_HASH,
	ESBIMGBOOT_PAYLOAD_BAD_SIGNATURE,
	ESBIMGBOOT_PAYLOAD_BAD_FW_COUNTER,
	ESBIMGBOOT_MALLOC_ERR
};
